[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "2.0.90", features = ["full", "printing", "extra-traits"]}
quote = "1.0.37"
proc-macro2 = "1.0.92"
lazy_static = "1.5.0"